In [3]:
import pandas as pd
url='/content/sample_data/Tweets.csv'
df=pd.read_csv(url)
df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [4]:
df.shape

(14640, 15)

In [5]:
df = df[["airline_sentiment", "text"]]

In [6]:
df.shape

(14640, 2)

In [7]:
import nltk
import string
import re

from nltk.stem.porter import PorterStemmer

nltk.download('stopwords')
from nltk.corpus import stopwords

nltk.download('punkt')
ps = PorterStemmer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http.?://[^\s]+[\s]?', '', text)
    tokens = nltk.word_tokenize(text)
    y = []
    for i in tokens:
        if i not in stopwords.words('english'):
            y.append(i)
    text = y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))
    return " ".join(y)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [8]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [9]:
df['cleaned_text'] = df['text'].apply(clean_text)

In [10]:
print(df[['text', 'cleaned_text']].head())

                                                text  \
0                @VirginAmerica What @dhepburn said.
1  @VirginAmerica plus you've added commercials t...
2  @VirginAmerica I didn't today... Must mean I n...
3  @VirginAmerica it's really aggressive to blast...
4  @VirginAmerica and it's a really big bad thing...

                                        cleaned_text
0                  @ virginamerica @ dhepburn said .
1  @ virginamerica plu 've ad commerci experi ......
2  @ virginamerica n't today ... must mean need t...
3  @ virginamerica 's realli aggress blast obnoxi...
4            @ virginamerica 's realli big bad thing

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)

X = tfidf.fit_transform(df['cleaned_text']).toarray()

Y = df['airline_sentiment'].values

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [13]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

model = MultinomialNB()

model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

accuracy = accuracy_score(Y_test, Y_pred)

print("Accuracy of the model:", accuracy)

Accuracy of the model: 0.7213114754098361

In [14]:
def predict_sentiment(new_text):

    cleaned = clean_text(new_text)

    vector = tfidf.transform([cleaned]).toarray()

    pred = model.predict(vector)[0]

    return pred

In [15]:
from sklearn.naive_bayes import MultinomialNB


model = MultinomialNB()
model.fit(X_train, Y_train)

MultinomialNB()

In [22]:


  word =input("enter the word : ")
  print(predict_sentiment(word))

enter the word : i cant do it
negative

In [17]:
df.groupby('airline_sentiment').describe()

                   text         \
                  count unique
airline_sentiment
negative           9178   9087
neutral            3099   3067
positive           2363   2298

                                                                           \
                                                                 top freq
airline_sentiment
negative           @AmericanAir robocalls me with another Cancell...    2
neutral                                           @SouthwestAir sent    5
positive                                              @united thanks    5

                  cleaned_text         \
                         count unique
airline_sentiment
negative                  9178   9083
neutral                   3099   3025
positive                  2363   2262


                                                                 top freq
airline_sentiment
negative           @ americanair , alway reli fli usair american ...    2
neutral            @ jetblu 's ceo battl appeas passeng wall stre...    8
positive                                            @ jetblu thank !   12